/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsIndexRouteImport } from './routes/listings/index'
import { Route as UserUserIdRouteImport } from './routes/user/$userId'
import { Route as ItemItemIdRouteImport } from './routes/item/$itemId'
import { Route as AppUserRouteRouteImport } from './routes/app/user/route'
import { Route as AppUserIndexRouteImport } from './routes/app/user/index'
import { Route as AppUserProductsIndexRouteImport } from './routes/app/user/products/index'
import { Route as AppUserProductsNewIndexRouteImport } from './routes/app/user/products/new/index'
import { Route as AppUserProductsEditItemIdRouteImport } from './routes/app/user/products/edit/$itemId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIndexRoute = ListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserIdRoute = UserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemItemIdRoute = ItemItemIdRouteImport.update({
  id: '/item/$itemId',
  path: '/item/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUserRouteRoute = AppUserRouteRouteImport.update({
  id: '/app/user',
  path: '/app/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUserIndexRoute = AppUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUserRouteRoute,
} as any)
const AppUserProductsIndexRoute = AppUserProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppUserRouteRoute,
} as any)
const AppUserProductsNewIndexRoute = AppUserProductsNewIndexRouteImport.update({
  id: '/products/new/',
  path: '/products/new/',
  getParentRoute: () => AppUserRouteRoute,
} as any)
const AppUserProductsEditItemIdRoute =
  AppUserProductsEditItemIdRouteImport.update({
    id: '/products/edit/$itemId',
    path: '/products/edit/$itemId',
    getParentRoute: () => AppUserRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-up': typeof SignUpRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/user': typeof AppUserRouteRouteWithChildren
  '/item/$itemId': typeof ItemItemIdRoute
  '/user/$userId': typeof UserUserIdRoute
  '/listings': typeof ListingsIndexRoute
  '/app/user/': typeof AppUserIndexRoute
  '/app/user/products': typeof AppUserProductsIndexRoute
  '/app/user/products/edit/$itemId': typeof AppUserProductsEditItemIdRoute
  '/app/user/products/new': typeof AppUserProductsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-up': typeof SignUpRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/user/$userId': typeof UserUserIdRoute
  '/listings': typeof ListingsIndexRoute
  '/app/user': typeof AppUserIndexRoute
  '/app/user/products': typeof AppUserProductsIndexRoute
  '/app/user/products/edit/$itemId': typeof AppUserProductsEditItemIdRoute
  '/app/user/products/new': typeof AppUserProductsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-up': typeof SignUpRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/user': typeof AppUserRouteRouteWithChildren
  '/item/$itemId': typeof ItemItemIdRoute
  '/user/$userId': typeof UserUserIdRoute
  '/listings/': typeof ListingsIndexRoute
  '/app/user/': typeof AppUserIndexRoute
  '/app/user/products/': typeof AppUserProductsIndexRoute
  '/app/user/products/edit/$itemId': typeof AppUserProductsEditItemIdRoute
  '/app/user/products/new/': typeof AppUserProductsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-up'
    | '/unauthorized'
    | '/app/user'
    | '/item/$itemId'
    | '/user/$userId'
    | '/listings'
    | '/app/user/'
    | '/app/user/products'
    | '/app/user/products/edit/$itemId'
    | '/app/user/products/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-up'
    | '/unauthorized'
    | '/item/$itemId'
    | '/user/$userId'
    | '/listings'
    | '/app/user'
    | '/app/user/products'
    | '/app/user/products/edit/$itemId'
    | '/app/user/products/new'
  id:
    | '__root__'
    | '/'
    | '/sign-up'
    | '/unauthorized'
    | '/app/user'
    | '/item/$itemId'
    | '/user/$userId'
    | '/listings/'
    | '/app/user/'
    | '/app/user/products/'
    | '/app/user/products/edit/$itemId'
    | '/app/user/products/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignUpRoute: typeof SignUpRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AppUserRouteRoute: typeof AppUserRouteRouteWithChildren
  ItemItemIdRoute: typeof ItemItemIdRoute
  UserUserIdRoute: typeof UserUserIdRoute
  ListingsIndexRoute: typeof ListingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/': {
      id: '/listings/'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$userId': {
      id: '/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof UserUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$itemId': {
      id: '/item/$itemId'
      path: '/item/$itemId'
      fullPath: '/item/$itemId'
      preLoaderRoute: typeof ItemItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/user': {
      id: '/app/user'
      path: '/app/user'
      fullPath: '/app/user'
      preLoaderRoute: typeof AppUserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/user/': {
      id: '/app/user/'
      path: '/'
      fullPath: '/app/user/'
      preLoaderRoute: typeof AppUserIndexRouteImport
      parentRoute: typeof AppUserRouteRoute
    }
    '/app/user/products/': {
      id: '/app/user/products/'
      path: '/products'
      fullPath: '/app/user/products'
      preLoaderRoute: typeof AppUserProductsIndexRouteImport
      parentRoute: typeof AppUserRouteRoute
    }
    '/app/user/products/new/': {
      id: '/app/user/products/new/'
      path: '/products/new'
      fullPath: '/app/user/products/new'
      preLoaderRoute: typeof AppUserProductsNewIndexRouteImport
      parentRoute: typeof AppUserRouteRoute
    }
    '/app/user/products/edit/$itemId': {
      id: '/app/user/products/edit/$itemId'
      path: '/products/edit/$itemId'
      fullPath: '/app/user/products/edit/$itemId'
      preLoaderRoute: typeof AppUserProductsEditItemIdRouteImport
      parentRoute: typeof AppUserRouteRoute
    }
  }
}

interface AppUserRouteRouteChildren {
  AppUserIndexRoute: typeof AppUserIndexRoute
  AppUserProductsIndexRoute: typeof AppUserProductsIndexRoute
  AppUserProductsEditItemIdRoute: typeof AppUserProductsEditItemIdRoute
  AppUserProductsNewIndexRoute: typeof AppUserProductsNewIndexRoute
}

const AppUserRouteRouteChildren: AppUserRouteRouteChildren = {
  AppUserIndexRoute: AppUserIndexRoute,
  AppUserProductsIndexRoute: AppUserProductsIndexRoute,
  AppUserProductsEditItemIdRoute: AppUserProductsEditItemIdRoute,
  AppUserProductsNewIndexRoute: AppUserProductsNewIndexRoute,
}

const AppUserRouteRouteWithChildren = AppUserRouteRoute._addFileChildren(
  AppUserRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignUpRoute: SignUpRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AppUserRouteRoute: AppUserRouteRouteWithChildren,
  ItemItemIdRoute: ItemItemIdRoute,
  UserUserIdRoute: UserUserIdRoute,
  ListingsIndexRoute: ListingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
